### ISSUE TITLE
[FR]: Integrate this generator in the normal craft cli when it is installed

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/generator#10]
It would be neat if the default `php craft` command can detect if this tool is installed, and list it's options so people can see all options easily.

**Comment by brandonkelly** [comment]
The `make` command will be shown when you run `php craft help`. Omitting each of the individual `make` subcommands was an intentional choice though (suggested [here](https://github.com/craftcms/cms/pull/12408#issuecomment-1332977734)).
