### ISSUE TITLE
Default input for module "What should the root namespace for ... be?" doesn't work

### ISSUE THREAD

**Issue by khalwat** [craftcms/generator#2]
### Description

Hitting `<return>` to accept the default root namespace for a module results in `Invalid input.`

```
/var/www/project/cms_v4 $ php craft make module
Module ID: (kebab-case) woof
Module location: [modules/woof] 
What should the root namespace for modules/woof/ be? 
Invalid input.
What should the root namespace for modules/woof/ be? 
Invalid input.
What should the root namespace for modules/woof/ be? 
Invalid input.
What should the root namespace for modules/woof/ be? 
```

I'd expect that it would just use what it was offering as a default.

### Steps to reproduce

1. `php craft make module`
2. hit `<return>` when it asks "What should the root namespace for ... be?"

### Additional info

n/a

**Comment by brandonkelly** [comment]
It’s asking for a root namespace, not a root location.

It will only ask for a root namespace if the default provided location isn’t autoloadable to begin with. In your case that means that you don’t have a preexisting autoload root for `modules/` or `modules/woof/` yet in composer.json. So a new autoload root will need to be created that points to `modules/woof/`.

**Comment by khalwat** [comment]
Shouldn't it be suggesting a sane default here tho?

**Comment by brandonkelly** [comment]
Fair. A default namespace is now suggested based on the module location, as of 1.0.3.
