### ISSUE TITLE
missing return type on init method

### ISSUE THREAD

**Issue by acalvino4** [craftcms/generator#20]
### Description

Not technically a bug, but an extra phpstan warning that could be avoided by default. Currently the generator doesn't add a return type on the module's `init` method, which throws an immediate phpstan warning.

### Steps to reproduce

1. Create new module with phpstan type checking enabled
2. run phpstan and observe warning: "Method modules\mymodule\Module::init() has no return type specified."

I am pretty sure this goes for plugins as well.

Should be as straightforward as `$class->getMethod('init')->setReturnType('void');` in `generators/Module.php` > `writeModuleClass`

### Additional info

- Craft version: any
- PHP version: any
- Database driver & version: any
- Plugins & versions: any

**Comment by brandonkelly** [comment]
Good call, and thanks for the PR! Merged in for the next release, however that will need to go out after Craft 4.4.11 is released as it depends on a pending bug fix (craftcms/cms@c371e21977aef2cde85dd1ba4c91bcb456b884db).

**Comment by brandonkelly** [comment]
Generator 1.5.0 is out with those changes. Thanks again!
