### ISSUE TITLE
Adding service - yii\base\Module::config() isn't called

### ISSUE THREAD

**Issue by MangoMarcus** [craftcms/generator#24]
### Description

Running `php craft make service` states to add a method `public static function config()` to the module in order to register the service as a component, but that method isn't used anywhere by craft

![Screenshot 2023-07-25 at 16 11 43](https://github.com/craftcms/generator/assets/72021142/3c6073f5-976e-4197-9ef4-f0dee6e25d7b)

### Additional info

- Craft version: 4.4.16.1
- PHP version: 8.1.12

**Comment by brandonkelly** [comment]
Thanks for reporting that!

It was a bug to recommend adding a `config()` method there – that’s a plugin-specific feature. Modules are configured via `config/app.php`. So you should change this:

```php
'modules' => [
    'mymodule' => modules\mymodule\Module::class,
],
```

to:

```php
'modules' => [
    'mymodule' => [
        'class' => modules\mymodule\Module::class,
        'components' => [
            'myService' => modules\mymodule\services\MyService::class,
        ],
    ],
],
```

Generator 1.6.0 is out now with a fix for this. Going forward, services that are generated for a module will output this at the end:

<img width="781" alt="Console output at the end of a `craft make service` command for a module, showing that config/app.php should be updated to include the new service component" src="https://github.com/craftcms/generator/assets/47792/a36ef2c4-0c95-44a3-ba12-cdbbe9c6c8d1">
