### ISSUE TITLE
[4.x]: craft generator - generated element action class contains errors

### ISSUE THREAD

**Issue by piotrpog** [craftcms/generator#31]
### Description

New element action class generated by class generaor contains errors:

* `getTriggerHtml()` method return value type is set to `?string`, yet this method does not return anything. This makes Craft throw exception when we register this action class.
* JS syntaxt error:
```
validateSelection: (selectedItems) {
  return true;
},
```

### Craft CMS version

4.5.11.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! Looks like someone already raised a PR for both of your points: https://github.com/craftcms/generator/pull/30
