### ISSUE TITLE
Error generating element type in Craft 5

### ISSUE THREAD

**Issue by thomasvantuycom** [craftcms/generator#32]
### Description

Attempting to create an element type using the native generator within Craft 5 results in an error:
```bash
Exception 'ReflectionException' with message 'Method craft\base\Element::hasContent() does not exist'

in /var/www/html/vendor/craftcms/generator/src/BaseGenerator.php:553
```

### Steps to reproduce

1. `php craft make element-type --plugin=my-plugin`

### Additional info

- Craft version: 5.0.0-beta.1
- PHP version: 8.2
- Database driver & version: mysql-8.0:v1.22.6
- Plugins & versions: "craftcms/generator": "2.0.x-dev"

**Comment by brandonkelly** [comment]
Thanks for reporting that! Generator 2.0.0 was just tagged with a fix.
