### ISSUE TITLE
'Method craft\base\Utility::iconPath() does not exist' error when creating a plugin utility

### ISSUE THREAD

**Issue by russback** [craftcms/generator#34]
### Description
Running `php craft make utility --plugin=foo` returns the following error:

```php
Exception 'ReflectionException' with message 'Method craft\base\Utility::iconPath() does not exist'
in /var/www/html/vendor/craftcms/generator/src/BaseGenerator.php:553
```

The plugin this is running on has been updated ready for Craft 5.

### Steps to reproduce

1. Install Generator v2 on a Craft 5 beta project
2. Run the `make utility` command

### Additional info

- Craft version: 5.0.0-beta.6
- PHP version: 8.2
- Database driver & version: 
- Plugins & versions: Custom plugin requiring craft ^4.0.0|^5.0.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just tagged Generator 2.0.1 with a fix.
