### ISSUE TITLE
[craft make plugin] rejects composer package name that has numbers in it

### ISSUE THREAD

**Issue by wsydney76** [craftcms/generator#4]
### Description

We use numbers in the composer package name, which should be fine: https://getcomposer.org/doc/04-schema.md#name, but is rejected as `Invalid input`.

Looks like `'pattern' => '/^[a-z][a-z\\-]*\\/[a-z][a-z\\-]*$/',` is used, which is  too strict.

### Steps to reproduce

1. run `craft make plugin`
2. enter `wsydney76/testplugin` when prompted for `Composer package name`

### Additional info

- Craft version: 4.3.5
- PHP version:
- Database driver & version:
- Plugins & versions:

/ Klara

**Comment by khalwat** [comment]
Yep, I ran into this, too:

```
Composer package name: [nystudio/mistletoe] nystudio107/craft-mistletoe
Invalid input.
```

`nystudio107` as a company is banned. I feel attacked 😄

**Comment by brandonkelly** [comment]
Thanks for reporting! 1.0.3 is out now with Composer’s recommended package name pattern.
