### ISSUE TITLE
Prepend `craft-` for the Composer package name as a convention?

### ISSUE THREAD

**Issue by khalwat** [craftcms/generator#5]
### Description

From a discussion a long time ago, you recommended prefixing our Craft plugin repositories with `craft-` to namespace & distinguish them as Craft CMS plugins.

Given this input:

```
Plugin name: Mistletoe
Developer name: nystudio107
Plugin handle: [mistletoe] 
Plugin location: [plugins/mistletoe] /Users/andrew/webdev/craft_v4/mistletoe
```

It suggests this as the Composer package name:

```
Composer package name: [nystudio/mistletoe]
```

Shouldn't it instead be `[nystudio/craft-mistletoe]`

Also, it shouldn't strip out the `107` from `nystudio107`

### Steps to reproduce

n/a

### Additional info

n/a

**Comment by brandonkelly** [comment]
Good idea! Just released 1.0.3 with this change.
