### ISSUE TITLE
require-dev.craftcms/ecs : NULL value found, but a string is required 

### ISSUE THREAD

**Issue by bymayo** [craftcms/generator#9]
### Description

When running anything with Composer e.g. `composer require x/y` I get an error `craftcms/ecs` and `craftcms/phpstan` mainly because I opted out of these when using the generator. I resolved this by just removing it from `require-dev` in `composer.json` but obviously the generator doesn't need to add this in.

### Steps to reproduce

1. Run generator to make a plugin
2. Opt out of ecs and phpstan
3. Try installing any composer package

### Additional info

- Craft version: 4.3.6.1
- PHP version: 8.1.12
- Database driver & version: MySQL 5.7
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Generator 1.2.0 which includes a fix.
